# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/andresmmera/git/qucs_s

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/andresmmera/git/qucs_s/qucs-s-spar-viewer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/andresmmera/git/qucs_s/qucs-s-spar-viewer/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Runtime\" \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andresmmera/git/qucs_s/qucs-s-spar-viewer/CMakeFiles /home/andresmmera/git/qucs_s/qucs-s-spar-viewer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/andresmmera/git/qucs_s/qucs-s-spar-viewer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named qucs-s

# Build rule for target.
qucs-s: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qucs-s
.PHONY : qucs-s

# fast build rule for target.
qucs-s/fast:
	$(MAKE) $(MAKESILENT) -f qucs/CMakeFiles/qucs-s.dir/build.make qucs/CMakeFiles/qucs-s.dir/build
.PHONY : qucs-s/fast

#=============================================================================
# Target rules for targets named qt3_compat

# Build rule for target.
qt3_compat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qt3_compat
.PHONY : qt3_compat

# fast build rule for target.
qt3_compat/fast:
	$(MAKE) $(MAKESILENT) -f qucs/qt3_compat/CMakeFiles/qt3_compat.dir/build.make qucs/qt3_compat/CMakeFiles/qt3_compat.dir/build
.PHONY : qt3_compat/fast

#=============================================================================
# Target rules for targets named components

# Build rule for target.
components: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 components
.PHONY : components

# fast build rule for target.
components/fast:
	$(MAKE) $(MAKESILENT) -f qucs/components/CMakeFiles/components.dir/build.make qucs/components/CMakeFiles/components.dir/build
.PHONY : components/fast

#=============================================================================
# Target rules for targets named diagrams

# Build rule for target.
diagrams: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 diagrams
.PHONY : diagrams

# fast build rule for target.
diagrams/fast:
	$(MAKE) $(MAKESILENT) -f qucs/diagrams/CMakeFiles/diagrams.dir/build.make qucs/diagrams/CMakeFiles/diagrams.dir/build
.PHONY : diagrams/fast

#=============================================================================
# Target rules for targets named dialogs

# Build rule for target.
dialogs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dialogs
.PHONY : dialogs

# fast build rule for target.
dialogs/fast:
	$(MAKE) $(MAKESILENT) -f qucs/dialogs/CMakeFiles/dialogs.dir/build.make qucs/dialogs/CMakeFiles/dialogs.dir/build
.PHONY : dialogs/fast

#=============================================================================
# Target rules for targets named paintings

# Build rule for target.
paintings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 paintings
.PHONY : paintings

# fast build rule for target.
paintings/fast:
	$(MAKE) $(MAKESILENT) -f qucs/paintings/CMakeFiles/paintings.dir/build.make qucs/paintings/CMakeFiles/paintings.dir/build
.PHONY : paintings/fast

#=============================================================================
# Target rules for targets named extsimkernels

# Build rule for target.
extsimkernels: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 extsimkernels
.PHONY : extsimkernels

# fast build rule for target.
extsimkernels/fast:
	$(MAKE) $(MAKESILENT) -f qucs/extsimkernels/CMakeFiles/extsimkernels.dir/build.make qucs/extsimkernels/CMakeFiles/extsimkernels.dir/build
.PHONY : extsimkernels/fast

#=============================================================================
# Target rules for targets named spicecomponents

# Build rule for target.
spicecomponents: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 spicecomponents
.PHONY : spicecomponents

# fast build rule for target.
spicecomponents/fast:
	$(MAKE) $(MAKESILENT) -f qucs/spicecomponents/CMakeFiles/spicecomponents.dir/build.make qucs/spicecomponents/CMakeFiles/spicecomponents.dir/build
.PHONY : spicecomponents/fast

#=============================================================================
# Target rules for targets named qucs-sactivefilter

# Build rule for target.
qucs-sactivefilter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qucs-sactivefilter
.PHONY : qucs-sactivefilter

# fast build rule for target.
qucs-sactivefilter/fast:
	$(MAKE) $(MAKESILENT) -f qucs-activefilter/CMakeFiles/qucs-sactivefilter.dir/build.make qucs-activefilter/CMakeFiles/qucs-sactivefilter.dir/build
.PHONY : qucs-sactivefilter/fast

#=============================================================================
# Target rules for targets named qucs-sattenuator

# Build rule for target.
qucs-sattenuator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qucs-sattenuator
.PHONY : qucs-sattenuator

# fast build rule for target.
qucs-sattenuator/fast:
	$(MAKE) $(MAKESILENT) -f qucs-attenuator/CMakeFiles/qucs-sattenuator.dir/build.make qucs-attenuator/CMakeFiles/qucs-sattenuator.dir/build
.PHONY : qucs-sattenuator/fast

#=============================================================================
# Target rules for targets named qucs-sfilter

# Build rule for target.
qucs-sfilter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qucs-sfilter
.PHONY : qucs-sfilter

# fast build rule for target.
qucs-sfilter/fast:
	$(MAKE) $(MAKESILENT) -f qucs-filter/CMakeFiles/qucs-sfilter.dir/build.make qucs-filter/CMakeFiles/qucs-sfilter.dir/build
.PHONY : qucs-sfilter/fast

#=============================================================================
# Target rules for targets named transcalc

# Build rule for target.
transcalc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 transcalc
.PHONY : transcalc

# fast build rule for target.
transcalc/fast:
	$(MAKE) $(MAKESILENT) -f qucs-transcalc/CMakeFiles/transcalc.dir/build.make qucs-transcalc/CMakeFiles/transcalc.dir/build
.PHONY : transcalc/fast

#=============================================================================
# Target rules for targets named qucs-strans

# Build rule for target.
qucs-strans: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qucs-strans
.PHONY : qucs-strans

# fast build rule for target.
qucs-strans/fast:
	$(MAKE) $(MAKESILENT) -f qucs-transcalc/CMakeFiles/qucs-strans.dir/build.make qucs-transcalc/CMakeFiles/qucs-strans.dir/build
.PHONY : qucs-strans/fast

#=============================================================================
# Target rules for targets named qucs-spowercombining

# Build rule for target.
qucs-spowercombining: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qucs-spowercombining
.PHONY : qucs-spowercombining

# fast build rule for target.
qucs-spowercombining/fast:
	$(MAKE) $(MAKESILENT) -f qucs-powercombining/CMakeFiles/qucs-spowercombining.dir/build.make qucs-powercombining/CMakeFiles/qucs-spowercombining.dir/build
.PHONY : qucs-spowercombining/fast

#=============================================================================
# Target rules for targets named qucs-sspar-viewer

# Build rule for target.
qucs-sspar-viewer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qucs-sspar-viewer
.PHONY : qucs-sspar-viewer

# fast build rule for target.
qucs-sspar-viewer/fast:
	$(MAKE) $(MAKESILENT) -f qucs-s-spar-viewer/CMakeFiles/qucs-sspar-viewer.dir/build.make qucs-s-spar-viewer/CMakeFiles/qucs-sspar-viewer.dir/build
.PHONY : qucs-sspar-viewer/fast

#=============================================================================
# Target rules for targets named uninstall-core

# Build rule for target.
uninstall-core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall-core
.PHONY : uninstall-core

# fast build rule for target.
uninstall-core/fast:
	$(MAKE) $(MAKESILENT) -f qucsator_rf/CMakeFiles/uninstall-core.dir/build.make qucsator_rf/CMakeFiles/uninstall-core.dir/build
.PHONY : uninstall-core/fast

#=============================================================================
# Target rules for targets named gperfappgen

# Build rule for target.
gperfappgen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gperfappgen
.PHONY : gperfappgen

# fast build rule for target.
gperfappgen/fast:
	$(MAKE) $(MAKESILENT) -f qucsator_rf/src/CMakeFiles/gperfappgen.dir/build.make qucsator_rf/src/CMakeFiles/gperfappgen.dir/build
.PHONY : gperfappgen/fast

#=============================================================================
# Target rules for targets named qucsator_rf

# Build rule for target.
qucsator_rf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qucsator_rf
.PHONY : qucsator_rf

# fast build rule for target.
qucsator_rf/fast:
	$(MAKE) $(MAKESILENT) -f qucsator_rf/src/CMakeFiles/qucsator_rf.dir/build.make qucsator_rf/src/CMakeFiles/qucsator_rf.dir/build
.PHONY : qucsator_rf/fast

#=============================================================================
# Target rules for targets named libqucsator

# Build rule for target.
libqucsator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libqucsator
.PHONY : libqucsator

# fast build rule for target.
libqucsator/fast:
	$(MAKE) $(MAKESILENT) -f qucsator_rf/src/CMakeFiles/libqucsator.dir/build.make qucsator_rf/src/CMakeFiles/libqucsator.dir/build
.PHONY : libqucsator/fast

#=============================================================================
# Target rules for targets named equation

# Build rule for target.
equation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 equation
.PHONY : equation

# fast build rule for target.
equation/fast:
	$(MAKE) $(MAKESILENT) -f qucsator_rf/src/CMakeFiles/equation.dir/build.make qucsator_rf/src/CMakeFiles/equation.dir/build
.PHONY : equation/fast

#=============================================================================
# Target rules for targets named coreInterface

# Build rule for target.
coreInterface: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 coreInterface
.PHONY : coreInterface

# fast build rule for target.
coreInterface/fast:
	$(MAKE) $(MAKESILENT) -f qucsator_rf/src/interface/CMakeFiles/coreInterface.dir/build.make qucsator_rf/src/interface/CMakeFiles/coreInterface.dir/build
.PHONY : coreInterface/fast

#=============================================================================
# Target rules for targets named coreComponents

# Build rule for target.
coreComponents: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 coreComponents
.PHONY : coreComponents

# fast build rule for target.
coreComponents/fast:
	$(MAKE) $(MAKESILENT) -f qucsator_rf/src/components/CMakeFiles/coreComponents.dir/build.make qucsator_rf/src/components/CMakeFiles/coreComponents.dir/build
.PHONY : coreComponents/fast

#=============================================================================
# Target rules for targets named coreDigital

# Build rule for target.
coreDigital: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 coreDigital
.PHONY : coreDigital

# fast build rule for target.
coreDigital/fast:
	$(MAKE) $(MAKESILENT) -f qucsator_rf/src/components/digital/CMakeFiles/coreDigital.dir/build.make qucsator_rf/src/components/digital/CMakeFiles/coreDigital.dir/build
.PHONY : coreDigital/fast

#=============================================================================
# Target rules for targets named coreDevices

# Build rule for target.
coreDevices: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 coreDevices
.PHONY : coreDevices

# fast build rule for target.
coreDevices/fast:
	$(MAKE) $(MAKESILENT) -f qucsator_rf/src/components/devices/CMakeFiles/coreDevices.dir/build.make qucsator_rf/src/components/devices/CMakeFiles/coreDevices.dir/build
.PHONY : coreDevices/fast

#=============================================================================
# Target rules for targets named coreMicrostrip

# Build rule for target.
coreMicrostrip: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 coreMicrostrip
.PHONY : coreMicrostrip

# fast build rule for target.
coreMicrostrip/fast:
	$(MAKE) $(MAKESILENT) -f qucsator_rf/src/components/microstrip/CMakeFiles/coreMicrostrip.dir/build.make qucsator_rf/src/components/microstrip/CMakeFiles/coreMicrostrip.dir/build
.PHONY : coreMicrostrip/fast

#=============================================================================
# Target rules for targets named coreMath

# Build rule for target.
coreMath: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 coreMath
.PHONY : coreMath

# fast build rule for target.
coreMath/fast:
	$(MAKE) $(MAKESILENT) -f qucsator_rf/src/math/CMakeFiles/coreMath.dir/build.make qucsator_rf/src/math/CMakeFiles/coreMath.dir/build
.PHONY : coreMath/fast

#=============================================================================
# Target rules for targets named defs

# Build rule for target.
defs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 defs
.PHONY : defs

# fast build rule for target.
defs/fast:
	$(MAKE) $(MAKESILENT) -f qucsator_rf/src/converter/CMakeFiles/defs.dir/build.make qucsator_rf/src/converter/CMakeFiles/defs.dir/build
.PHONY : defs/fast

#=============================================================================
# Target rules for targets named qucsconv_rf

# Build rule for target.
qucsconv_rf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qucsconv_rf
.PHONY : qucsconv_rf

# fast build rule for target.
qucsconv_rf/fast:
	$(MAKE) $(MAKESILENT) -f qucsator_rf/src/converter/CMakeFiles/qucsconv_rf.dir/build.make qucsator_rf/src/converter/CMakeFiles/qucsconv_rf.dir/build
.PHONY : qucsconv_rf/fast

#=============================================================================
# Target rules for targets named translations

# Build rule for target.
translations: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 translations
.PHONY : translations

# fast build rule for target.
translations/fast:
	$(MAKE) $(MAKESILENT) -f translations/CMakeFiles/translations.dir/build.make translations/CMakeFiles/translations.dir/build
.PHONY : translations/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... defs"
	@echo "... equation"
	@echo "... translations"
	@echo "... uninstall"
	@echo "... uninstall-core"
	@echo "... components"
	@echo "... coreComponents"
	@echo "... coreDevices"
	@echo "... coreDigital"
	@echo "... coreInterface"
	@echo "... coreMath"
	@echo "... coreMicrostrip"
	@echo "... diagrams"
	@echo "... dialogs"
	@echo "... extsimkernels"
	@echo "... gperfappgen"
	@echo "... libqucsator"
	@echo "... paintings"
	@echo "... qt3_compat"
	@echo "... qucs-s"
	@echo "... qucs-sactivefilter"
	@echo "... qucs-sattenuator"
	@echo "... qucs-sfilter"
	@echo "... qucs-spowercombining"
	@echo "... qucs-sspar-viewer"
	@echo "... qucs-strans"
	@echo "... qucsator_rf"
	@echo "... qucsconv_rf"
	@echo "... spicecomponents"
	@echo "... transcalc"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

